# Generated by Django 5.1.5 on 2025-02-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
